CREATE TABLE TEAMS{
    ID BIGINT PRIMARY KEY NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
}